name: ng_bootstrap_demo
version: 0.0.1
description: ng_bootstrap demo gh-page
authors:
  - Luis Vargas <luisvargastijerino@gmail.com>
  - Adao Jr. <itsjunnior@gmail.com>
dependencies:
  string_converters: ^1.0.0
  angular: 6.0.1
  dson: ^0.18.0
#  ng_bootstrap: ^0.6.3
  ng_bootstrap:
    path: ..
#    git: https://github.com/dart-league/ng_bootstrap
dev_dependencies:
  sass_builder: ^2.1.1
#  sass_builder:
#    path: ../sass_builder
  build_runner: ^1.10.3
  build_web_compilers: ^2.12.0
